name: Run Selenium Automation

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'    # runs daily at 4am UTC; adjust as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium python-dotenv

      # Not usually needed, but if Chrome version mismatch errors appear, add:
      # - name: Install Google Chrome
      #   run: |
      #     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      #     sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Run Script
        run: python naukri_resume_updater.py

    env:
      NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
      NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
      NAUKRI_RESUME_URL: ${{ secrets.NAUKRI_RESUME_URL }}
