name: Update Naukri Resume

on:
  schedule:
    - cron: "0 2,8,14 * * *" # Every day at 2AM, 8AM, 2PM UTC
  workflow_dispatch: # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install selenium python-dotenv

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run script
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
          NAUKRI_RESUME_URL: ${{ secrets.NAUKRI_RESUME_URL }}
        run: |
          python naukri_resume_updater.py
