name: Naukri Resume Upload

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # Daily at 4 AM UTC

jobs:
  upload-resume:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install selenium==4.15.2 python-dotenv==1.0.0

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Verify Chrome installation
        run: |
          google-chrome --version
          which chromedriver
          chromedriver --version

      - name: Run automation script
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
          NAUKRI_RESUME_URL: ${{ github.workspace }}/resume.pdf
        run: python naukri_resume_updater.py
