name: Update Naukri Resume

on:
  schedule:
    - cron: "0 2,8,14 * * *" # Run daily at 2AM, 8AM, 2PM UTC
  workflow_dispatch:

jobs:
  update-resume:
    runs-on: ubuntu-latest

    steps:
      - name: 📁 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install Python dependencies
        run: |
          pip install selenium python-dotenv

      - name: 🌐 Install Google Chrome v114
        run: |
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.110-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_114.0.5735.110-1_amd64.deb

      - name: 🧩 Install ChromeDriver v114.0.5735.90
        run: |
          wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip -o /tmp/chromedriver.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: ▶️ Run resume update script
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
          NAUKRI_RESUME_URL: ${{ secrets.NAUKRI_RESUME_URL }}
        run: |
          python naukri_resume_updater.py
